[agent]
provider = "openrouter"
model = "deepseek/deepseek-v4-flash"
tools = []
logging = false  # false | true | "debug"

[access]
allow_by_default = false
interfaces = ["telegram", "cli"]

[memory]
max_messages = 10

[environment]
PBANK_HOME = "{{$agentpath}}/.data/tools/pbank"

# [audio]
# provider = "whisper"  # or http://localhost:9000/v1 for local whisper server
# model = "whisper-1"
