[agent]
provider = "openrouter"
model = "openai/gpt-oss-20b:free"
tools = []
logging = false  # false | true | "debug"

[access]
allow_by_default = false
interfaces = ["telegram", "cli"]

[memory]
max_messages = 10

[advanced]
reasoning_carryover = "tools"  # none|tools|all
reasoning_effort = "low"    # minimal|low|medium|high|max

# [audio]
# provider = "whisper"  # or http://localhost:9000/v1 for local whisper server
# model = "whisper-1"
