#!/usr/bin/env bash
# Auto-generated by agentctl init
# Runs before each agent execution for setup/validation

# Auto-load prerun scripts from individual tools (e.g., tools/memory/.prerun.sh)
for dir in tools/*/; do
    [ -f "${dir}.prerun.sh" ] && source "${dir}.prerun.sh" && continue
    [ -f "${dir}prerun.sh" ] && source "${dir}prerun.sh"
    true
done

# Add your custom setup logic below
