command = "pbank balance"
description = "Show current balances for all funds"
report = "check balance"

[pbank_home]
type = "string"
return = "{{$agentpath}}/.data/tools/pbank/{{$user}}"
env = "PBANK_HOME"
